/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prototipointerfaces;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author santiago
 */
public class ActualizarPassword extends javax.swing.JFrame {

    String cedula = MóduloAdministraciónSistema.nuevoUsuarioA.getCedula();
    String usuario = MóduloAdministraciónSistema.nuevoUsuarioA.getUsuario();
    String tipoUsuario = MóduloAdministraciónSistema.nuevoUsuarioA.getTipoUsuario();

    /**
     * Creates new form ActualizarDatoCliente
     */
    public ActualizarPassword() {
        initComponents();
        setLocationRelativeTo(null);
    }

    void actualizarPassword(String nuevaPassword) {
        Conexion con = new Conexion();
        Connection cn = (Connection) con.conexion();
        com.mysql.jdbc.PreparedStatement pstm;
        try {
            pstm = (com.mysql.jdbc.PreparedStatement) cn.prepareStatement("update usuarios set password = ? WHERE cedula LIKE ? AND usuario LIKE ? AND tipo_usuario LIKE ?");
            pstm.setString(1, nuevaPassword);
            pstm.setString(2, cedula);
            pstm.setString(3, usuario);
            pstm.setString(4, tipoUsuario);
            pstm.executeUpdate();
            JOptionPane.showMessageDialog(null, "¡Password del Usuario Actualzada Exitosamente!");
        } catch (Exception e) {
            System.err.println("Error: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtrasRP = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnConfirmarReseteo = new javax.swing.JButton();
        txtConfNuevaPasswordRP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNuevaPassword = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerente General");

        btnAtrasRP.setText("Atrás");
        btnAtrasRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasRPActionPerformed(evt);
            }
        });

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Resetear"));

        jLabel6.setText("Nueva Password");

        btnConfirmarReseteo.setText("Confirmar");
        btnConfirmarReseteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarReseteoActionPerformed(evt);
            }
        });

        jLabel7.setText("Confirmar Nueva Password");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtConfNuevaPasswordRP, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtNuevaPassword)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(btnConfirmarReseteo)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNuevaPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConfNuevaPasswordRP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(btnConfirmarReseteo)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAtrasRP)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btnAtrasRP)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasRPActionPerformed
        // TODO add your handling code here:
        MóduloAdministraciónSistema nuevoModAdmin = new MóduloAdministraciónSistema();
        nuevoModAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasRPActionPerformed

    private void btnConfirmarReseteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarReseteoActionPerformed
        // TODO add your handling code here:
        String nuevaPassword;
        String confirmada;
        if (txtNuevaPassword.getText().equals("")
                || txtConfNuevaPasswordRP.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Para actualizar la Password debe llenar TODOS los campos", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            nuevaPassword = txtNuevaPassword.getText();
            if (!MóduloAdministraciónSistema.nuevoUsuarioA.esPasswordValida(nuevaPassword)) {
                JOptionPane.showMessageDialog(null, "La nueva Password no cumple las condiciones - Corrija", "Error", JOptionPane.WARNING_MESSAGE);
                txtNuevaPassword.setText("");
                txtConfNuevaPasswordRP.setText("");
            } else {
                confirmada = txtConfNuevaPasswordRP.getText();
                if (!confirmada.equals(nuevaPassword)) {
                    JOptionPane.showMessageDialog(null, "¡Las contraseñas no coinciden! - Vuelva a Ingresar", "Error", JOptionPane.WARNING_MESSAGE);
                    txtConfNuevaPasswordRP.setText("");
                } else {
                    actualizarPassword(nuevaPassword);
                    //----------------------------------------------------------
                    MóduloAdministraciónSistema newMod = new MóduloAdministraciónSistema();
                    newMod.setVisible(true);
                    this.dispose();
                    //----------------------------------------------------------
                }
            }
        }
    }//GEN-LAST:event_btnConfirmarReseteoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtrasRP;
    private javax.swing.JButton btnConfirmarReseteo;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JTextField txtConfNuevaPasswordRP;
    private javax.swing.JTextField txtNuevaPassword;
    // End of variables declaration//GEN-END:variables
}
